version: '3'
services:
    redis:
      image: redis
      ports:
          - "6379:6379"
    sagal-mp:
        build: .
        depends_on:
            - redis
        links:
            - redis
        ports:
            - "80:8080"
        volumes:
            - ./files:/files
